### PR TITLE
Changed cross section files to current system

### PR DESCRIPTION
**Pull request by cmillera**
The tests may not work now, I followed the system from test1a but by looking at the XMLparser it doesn;t seem that will work, since it is looking for an xs_file attribute. Ilham can you please clear up this confusion?

### CODE REVIEW

**Comment by ilhamv** [comment]
Cameron,

I forgot to delete the scatter_cont, fission_cont, and xs_file. We don't need to use that anymore.
Therefore, instead of inputting

<nuclides>
    <nuclide name="U235" />
        <capture_cont xs_file="092235" />
        <scatter_cont xs_file="092235" ... />
        <fission_cont xs_file="092235" ... />
    </nuclide>
</nuclides>

We could just do
<nuclides>
    <092235 name="U235" />
</nuclides>
and we have everything set up automatically. The 092235 numbers should correspond to the 0922235.txt file, and the name attribute is required for reference in the material. That’s how I set the parser.

The usual user-specified (from scratch) nuclide feature is still there intact:
<nuclides>
    <nuclide name="nuc1" A=”12” />
        <capture xs="1.0" />
        <scatter xs_v="1.0 2.0" ... />
        <fission  xs="1.0" ... />
    </nuclide>
</nuclides>


Also, I'm confused why your pull request request to remove all the existing files, even if they are not changed (even the pugi*). Did you manually create a copy of the master, work on that somewhere, manually replace the files, then push? I got hard time to make sure that everything is still there the same.

It happened with Felicia, yet she found a way to go around that. Could you please give suggestion to address this, Fel? Once it's addressed, I'll merge the pull request and fix the confusion.

Thanks!
Ilham

**Comment by ilhamv** [comment]
It's weird, my comment got truncated. I split my comment into parts, then:

Cameron,

I forgot to delete the scatter_cont, fission_cont, and xs_file. We don't need to use that anymore.
Terefore, instead of inputting

<nuclides>
    <nuclide name="U235" />
        <capture_cont xs_file="092235" />
        <scatter_cont xs_file="092235" ... />
        <fission_cont xs_file="092235" ... />
</nuclides>

**Comment by ilhamv** [comment]
It looks like my comment got truncated by github. I'll email you, then.

**Comment by feliciasutanto** [comment]
What happened in my case was: I was working on the code somewhere else (I
copy pasted the entire files). Then after I finished working on my codes, I
copy pasted the entire files to my github folder. Then I pull-requested.
That's why Ilham got a request to replace all of the existing files.

I did not found any way to get by with this. Basically what I did was, I
re-downloaded the current github codes and I manually copy pasted changes
that I made on my code. Then I pull-requested again.

**Pull request closed without merging**
